name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: hello
      # run: echo "print('hello world')" > hello.py
      run: |
        chmod +x entrypoint.sh
        ./entrypoint.sh > hello.py

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ github.repository }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
